fanpage/urls.py
from django.urls import path
from . import views

app_name = "fanpage"

urlpatterns = [
    path("", views.PostListView.as_view(), name="list"),
    path("<uuid:public_id>", views.PostDetailView.as_view(), name="detail"),
    path("create", views.PostCreateView.as_view(), name="create"),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('fanpage.urls')),
]

fanpage/models.py
from django.db import models
import uuid

class Post(models.Model):

    public_id = models.UUIDField(default=uuid.uuid4, editable=False)

    active = models.BooleanField(default=True)

    author = models.CharField(max_length=64)

    post = models.TextField()
    
    created_on = models.DateTimeField(auto_now_add=True)

    last_modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.author

fanpage/forms.py
from django.forms import ModelForm
from django.core.exceptions import ValidationError

from . import models

class PostForm(ModelForm):
    class Meta:
        model = models.Post
        exclude = ("active",)

    def clean_post(self):
        min_words = 5

        data = self.cleaned_data["post"]

        if (data.count(" ") + data.count("\n")) < min_words:
            raise ValidationError(f"Post should have more than {min_words} words.")

        return data

fanpage/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView
from django.views import View
from django.urls import reverse_lazy

from . import models, forms

class PostListView(ListView):
    model = models.Post
    fields = "__all__"
    queryset = models.Post.objects.filter(active=True).order_by("-last_modified")

class PostDetailView(DetailView):
    model = models.Post
    
    def get_object(self, queryset=None):
        return self.model.objects.get(public_id=self.kwargs.get("public_id"))

class PostCreateView(CreateView):
    form_class = forms.PostForm
    template_name = "fanpage/post_form.html"
    success_url = reverse_lazy("fanpage:list")

fanpage/templates/fanpage/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        
        {% block title %}
        {% endblock title %}

        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <style>
        body {font-family: "Lato", sans-serif}
        .mySlides {display: none}
        </style>
    </head>
    <body>

        {% block content %}
        {% endblock content %}

        <!-- Footer -->
        <footer class="w3-container w3-padding-64 w3-center w3-opacity w3-light-grey w3-xlarge">
        <i class="fa fa-facebook-official w3-hover-opacity"></i>
        <i class="fa fa-instagram w3-hover-opacity"></i>
        <i class="fa fa-snapchat w3-hover-opacity"></i>
        <i class="fa fa-pinterest-p w3-hover-opacity"></i>
        <i class="fa fa-twitter w3-hover-opacity"></i>
        <i class="fa fa-linkedin w3-hover-opacity"></i>
        <p class="w3-medium">Powered by <a href="#" target="">Flasky.</a></p>
    </footer>
    
    <script>
    // Automatic Slideshow - change image every 4 seconds
    var myIndex = 0;
    carousel();
    
    function carousel() {
        var i;
        var x = document.getElementsByClassName("mySlides");
        for (i = 0; i < x.length; i++) {
        x[i].style.display = "none";  
        }
        myIndex++;
        if (myIndex > x.length) {myIndex = 1}    
        x[myIndex-1].style.display = "block";  
        setTimeout(carousel, 4000);    
    }
    
    </script>
    </body>
  </html>

fanpage/templates/fanpage/post_detail.html
{% extends "fanpage/layout.html" %}
{% load static %}

{% block title %}
  <title> BTS Army </title>
{% endblock title %}

{% block content %}
  <nav class="navbar navbar-expand-lg navbar navbar-dark bg-dark">
    <a class="navbar-brand" href="#">
      <img src="{% static 'fanpage/btslogo.jpg' %}" width="30" height="30" class="d-inline-block align-top" alt="">
      BTS Army
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'fanpage:list' %}">Home</a>
        </li>
      </ul>
    </div>
  </nav>

  <!-- The Band Section -->
  {% if object.active %}
  <div class="w3-container w3-content w3-center w3-padding-64" style="max-width:800px" id="band">
    <h2 class="w3-wide">{{ object.author | title }}</h2>
    <p class="w3-opacity"><i>Time of posting: {{ object.created_on }}</i></p>
    {% if object.created_on != object.last_modified %}
    <p class="w3-opacity"><i>Last modified: {{ object.last_modified }}</i></p>
    {% endif %}
    <p class="w3-justify">{{ object.post }}</p>
    {% else %}
    <p class="w3-justify">This post have been deleted.</p>
  </div>
  {% endif %}

  <!-- End Page Content -->
  </div>
{% endblock content %}

fanpage/templates/fanpage/post_form.html
<form method="post">
    {% csrf_token %}
    
    {{ form.as_p }}

    {% if form.instance.pk %}
        <input type="submit" value="Update" />
    {% else %}
        <input type="submit" value="Create post" />
    {% endif %}
</form>

fanpage/templates/fanpage/post_list.html
{% extends "fanpage/layout.html" %}
{% load static %}

{% block title %}
  <title> Home </title>
{% endblock title %}

{% block content %}
  <nav class="navbar navbar-expand-lg navbar navbar-dark bg-dark">
    <a class="navbar-brand" href="#">
      <img src="{% static 'fanpage/btslogo.jpg' %}" width="30" height="30" class="d-inline-block align-top" alt="">
      BTS Army
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
      </ul>
        <a href="{% url 'fanpage:create' %}"><button class="btn btn-outline-light my-2 my-sm-0">Post</button></a>
    </div>
  </nav>

<!-- Page content -->
<div class="w3-content" style="max-width:2000px;margin-top:0px">

  <!-- Automatic Slideshow Images -->
  <div class="mySlides w3-display-container w3-center">
    <img src="{% static 'fanpage/bts2.jpg' %}" style="width:100%">
    <div class="w3-display-bottommiddle w3-container w3-text-white w3-padding-32 w3-hide-small">
      <h3>Baguio City</h3>
      <p><b>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.!</b></p>   
    </div>
  </div>
  <div class="mySlides w3-display-container w3-center">
    <img src="{% static 'fanpage/bts1.jpg' %}" style="width:100%">
    <div class="w3-display-bottommiddle w3-container w3-text-white w3-padding-32 w3-hide-small">
      <h3>La Trinidad City</h3>
      <p><b>Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur.</b></p>    
    </div>
  </div>
  <div class="mySlides w3-display-container w3-center">
    <img src="{% static 'fanpage/bts3.jpg' %}" style="width:100%">
    <div class="w3-display-bottommiddle w3-container w3-text-white w3-padding-32 w3-hide-small">
      <h3>Tuba City</h3>
      <p><b>Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur.</b></p>    
    </div>
  </div>

  <!-- The Band Section -->
  <div class="w3-container w3-content w3-center w3-padding-64" style="max-width:800px" id="band">
    <h2 class="w3-wide">BTS ARMY</h2>
    <p class="w3-opacity"><i>We love our KPOP Idols</i></p>
    <p class="w3-justify">Already millions strong, ARMY had a new recruit. BTS has been amassing a legion 
      of fans long before it became the first all-South Korean act to top the Billboard Hot 100 with “Dynamite,” 
      or set the world record for attracting the most viewers for a concert live stream during the coronavirus 
      pandemic. The septet’s fandom captured the attention of international media when it propelled the band 
      to win the fan-voted Top Social Artist, with more than 300 million votes, at the 2017 Billboard Music Awards. 
      BTS ended a six-year winning streak in the category by Justin Bieber and beat the likes Ariana Grande, 
      Shawn Mendes and Selena Gomez. At the time, Bieber boasted more than 100 million followers on Twitter, 
      and Grande was the third-most followed account on Instagram.</p>
    <div class="w3-row w3-padding-32">
      <div class="w3-third">
        <p>Flasky</p>
        <img src="{% static 'fanpage/fangirl.jpg' %}" class="w3-round w3-margin-bottom" alt="Random Name" style="width:60%">
      </div>
      <div class="w3-third">
        <p>Flasky</p>
        <img src="{% static 'fanpage/fangirl.jpg' %}" class="w3-round w3-margin-bottom" alt="Random Name" style="width:60%">
      </div>
      <div class="w3-third">
        <p>Flasky</p>
        <img src="{% static 'fanpage/fangirl.jpg' %}" class="w3-round" alt="Random Name" style="width:60%">
      </div>
    </div>
  </div>

  <!-- The Tour Section -->
  <div class="w3-black" id="tour">
    <div class="w3-container w3-content w3-padding-64" style="max-width:800px">
      <h2 class="w3-wide w3-center">FAN POSTS</h2>
      <p class="w3-opacity w3-center"><i>Already millions strong, ARMY had a new recruit!</i></p><br>

      <div class="w3-row-padding w3-padding-32" style="margin:0 -16px">
        {% for object in object_list %}
        {% if object.author %}
        <div class="w3-third w3-margin-bottom">
          <div class="w3-container w3-white">
            <p style="font-size: 24px;"><b>{{ object.author | title }}</b></p>
            {% else %}
            <p><b>Anonymous</b></p>
            {% endif %}
            <p class="w3-opacity" style="font-size: 11px;">Time of posting: {{ object.created_on }}</p>
            {% if object.created_on != object.last_modified %}
            <p class="w3-opacity">Last modified: {{ object.last_modified }}</p>
            {% endif %}
            <hr>
            <p style="font-size: 14px;">{{ object.post | truncatewords:8}}</p>
            <hr>
            <a href="{% url "fanpage:detail" object.public_id %}" class="link-dark"><button class="w3-button w3-black w3-margin-bottom">Read more</button></a>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>

  <!-- End Page Content -->
  </div>

{% endblock content %}